dist: trusty
languaje: java
jdk: 
- openjdk10
services:
- postgresql
addons:
  firefox: "70.0"
  sonarcloud:
    organization: "prosubjectgrupo5"
    token:
      secure: "GRaIW9/YYqmk2kAC5rOJXyyAlprfgoFwisdUcg+fyBeRkJ4NVDMr+aKHU2AnVDtac6l9A+G79zAotvwANVgeln0uRCjunEbHS4PhBWXoIDYIhk3Aht1B9GiQLKw64MjiDFEZqE6KQ0Ou9MNQ+YqDtNjb4Sthpc4z0cDBf0BmyIAOKoGTYD2QcHmY8WkyRTtgx9pYGRfZ6XEj4rNUhXiEiurKHB9GTEAsU7PG2YoETU9n86Xoehczd+WnnB+rxywRKucw18HoNtppWdFJFT2SQZ7va5fTPxEIcTIAKBCejtoFPMgkNU3W5pE2Jp9agyejQuMCJhvo7cv5a0uc/wAkmxXoOHILhr2jGTJl7HQSaSh22OpIx+6ogGljHG/2Uh5BZ0p5PzVO8OQz7E33QGifwLZq1yDB6k+R3RO1TiPeB9l5tAja03+SMs8kS7Q1lYNkqSEV0jZhVgJ4llHjwxwmQV1NnIOkRRHVThSRkob9g1b1JF2a7y/VUPjUIg6wKr05On2V0DVLNGQn2vB0e6okcYNeVwoTcsBiKi9SurLrNiVLSYrUlez/Rf1mka6DDgUXnh3HkDGt3Bj0o+wTU7eFt5OdBDWEToYPZSBBY/FL8qLL/dOpyAkfdLc6oPSGfpEFeuJn7Ir2xSAk8bXDD5L8PB8KFX0Z3S+qaltBohro88o="
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=ProSubjectGrupo5_ProSubject-back-lanzamiento
install:
- ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
before_install:
- chmod +x mvnw 
- psql -c 'create database d84fcuj7llju5i;' -U postgres
on:
    branch: master



