dist: trusty
languaje: java
jdk: 
- openjdk10
services:
- postgresql
addons:
  firefox: "70.0"
  sonarcloud:
    organization: "prosubjectgrupo5"
    token:
      secure: "bRmdG2SJr7SwTadGHywg9GJI7tuh/d7/57WZrVOb9WuPIS8pd56DTx0bjueaPQM9q5jjpw7aZ8hOkl+LpXAu04ztTY0fMhUTWNuDsyOytTqBCOwJonLFSXzCtBAGbVRnQ6tCXsbJtNHq2/ukVZLZmWUS2fJzrr8a9yAcc/8CQUHcX1wNJlO/5dgdjg8Mfc6jixfZCcMCHMVaLfLWJ/0uXlan85UFw0krmDapF/iiK+53M4PhwKuBBF+ON0qx4u4NEpLeCt13aivs1Ix8kDORGH2wJWF0msTOfSMsurB3breJPF9D4of7/oBEhGyN8+D+7hw7+YrQLm9IQ7FezYquqkefAvHAAZnrL0qTFdX6JMNRMT1C0UyK62uaripY1IgasXW9cnKKwnp3jG96HmogKavrWTgGOh/rYy+ImsDP/s/WvzvLY9ivHxO7k6n071x39g0ukhgJIKKEnYLZggyFrpbdzeNACm/skbPmDbVYGwoFctbIS0ODGis1zlV/zd3ZNm+3hFHaQNtqaMyt2Y9gM0wMv9+lLiWHXFOkpKa8xsOU3rEICQHE5EH27pJS9ZNuQGmX2TK7q3CdiJLA4Ro4LGln6alV2c3DuLv31u3jDNGrn8FmCkBrH8DzdQfnmnWuIOpkjrMaW+bkuccrr4KMF2/NQ5L4a0MT6WjmdiqxXj0="
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=ProSubjectGrupo5_ProSubject-back-final
install:
- ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
before_install:
- chmod +x mvnw 
- psql -c 'create database dcu1a62i6ms7i4;' -U postgres
on:
    branch: master



